<?php

namespace Database\Seeders;

use App\Models\AboutPage;
use App\Models\Faq;
use App\Models\GalleryItem;
use App\Models\HomeBannerSlide;
use App\Models\HomepageSection;
use App\Models\PageHero;
use App\Models\Policy;
use App\Models\Testimonial;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class MarketingContentSeeder extends Seeder
{
    public function run(): void
    {
        foreach ([
            ['key' => 'hero', 'title_fr' => 'Asthetika · Dr Aziz Sahly', 'title_en' => 'Asthetika · Dr Aziz Sahly', 'content_fr' => 'Médecine esthétique et soins de la peau à La Soukra, Ariana.', 'content_en' => 'Aesthetic medicine and skincare in La Soukra, Ariana.', 'button_text_fr' => 'Prendre rendez-vous', 'button_text_en' => 'Book an appointment', 'button_url' => '/booking', 'secondary_button_text_fr' => 'Nous contacter', 'secondary_button_text_en' => 'Contact us', 'secondary_button_url' => '/contact', 'is_active' => true, 'sort_order' => 1],
            ['key' => 'intro', 'title_fr' => 'Une prise en charge esthétique personnalisée', 'title_en' => 'Personalized aesthetic care', 'content_fr' => 'Chez Asthetika, chaque soin est adapté à votre peau, vos besoins et vos objectifs, avec une approche professionnelle et attentive.', 'content_en' => 'At Asthetika, every treatment is adapted to your skin, your needs, and your goals with a professional and attentive approach.', 'is_active' => true, 'sort_order' => 2],
            ['key' => 'benefits', 'title_fr' => 'Pourquoi choisir Asthetika', 'title_en' => 'Why choose Asthetika', 'content_fr' => 'Protocoles personnalisés, hygiène rigoureuse, conseils adaptés et suivi attentif.', 'content_en' => 'Personalized protocols, rigorous hygiene, tailored advice, and attentive follow-up.', 'is_active' => true, 'sort_order' => 3],
            ['key' => 'categories', 'title_fr' => 'Noor & Dr Aziz', 'title_en' => 'Noor & Dr Aziz', 'content_fr' => 'Deux univers complémentaires : les soins de la peau Noor et l’accompagnement médico-esthétique par Dr Aziz Sahly.', 'content_en' => 'Two complementary care areas: Noor skincare treatments and medical-aesthetic guidance by Dr Aziz Sahly.', 'button_text_fr' => 'Découvrir les services', 'button_text_en' => 'Discover services', 'button_url' => '/services', 'is_active' => true, 'sort_order' => 4],
            ['key' => 'noor', 'title_fr' => 'Noor', 'title_en' => 'Noor', 'content_fr' => 'Soins de la peau, Hydrafacial et protocoles esthétiques personnalisés pour accompagner l’éclat et l’équilibre cutané.', 'content_en' => 'Skincare, Hydrafacial, and personalized aesthetic protocols to support radiance and skin balance.', 'button_text_fr' => 'Voir Noor', 'button_text_en' => 'View Noor', 'button_url' => '/services#noor', 'is_active' => true, 'sort_order' => 5],
            ['key' => 'dr_aziz', 'title_fr' => 'Dr Aziz', 'title_en' => 'Dr Aziz', 'content_fr' => 'Consultation, conseils personnalisés et accompagnement professionnel avec Dr Aziz Sahly.', 'content_en' => 'Consultation, personalized guidance, and professional care with Dr Aziz Sahly.', 'button_text_fr' => 'Voir Dr Aziz', 'button_text_en' => 'View Dr Aziz', 'button_url' => '/services#dr-aziz', 'is_active' => true, 'sort_order' => 6],
            ['key' => 'services', 'title_fr' => 'Soins et protocoles Asthetika', 'title_en' => 'Asthetika treatments and protocols', 'content_fr' => 'Découvrez les soins Noor et les consultations Dr Aziz selon vos besoins.', 'content_en' => 'Discover Noor treatments and Dr Aziz consultations according to your needs.', 'button_text_fr' => 'Voir les services', 'button_text_en' => 'View services', 'button_url' => '/services', 'is_active' => true, 'sort_order' => 7],
            ['key' => 'consultation', 'title_fr' => 'Besoin d’être orientée ?', 'title_en' => 'Need guidance?', 'content_fr' => 'Une consultation permet de mieux comprendre vos besoins et de choisir un protocole adapté.', 'content_en' => 'A consultation helps understand your needs and choose a suitable protocol.', 'button_text_fr' => 'Demander conseil', 'button_text_en' => 'Ask for guidance', 'button_url' => '/contact', 'is_active' => true, 'sort_order' => 8],
            ['key' => 'gallery', 'title_fr' => 'L’univers Asthetika', 'title_en' => 'The Asthetika experience', 'content_fr' => 'Un aperçu de l’ambiance, des soins et de l’approche Asthetika.', 'content_en' => 'A glimpse into Asthetika’s atmosphere, treatments, and approach.', 'button_text_fr' => 'Voir la galerie', 'button_text_en' => 'View gallery', 'button_url' => '/gallery', 'is_active' => true, 'sort_order' => 9],
            ['key' => 'testimonials', 'title_fr' => 'Retours d’expérience', 'title_en' => 'Client feedback', 'content_fr' => 'Des retours simples et authentiques sur l’accompagnement Asthetika.', 'content_en' => 'Simple and authentic feedback about the Asthetika experience.', 'button_text_fr' => 'Lire les avis', 'button_text_en' => 'Read reviews', 'button_url' => '/testimonials', 'is_active' => true, 'sort_order' => 10],
            ['key' => 'faq', 'title_fr' => 'Questions fréquentes', 'title_en' => 'Frequently asked questions', 'content_fr' => 'Retrouvez les réponses utiles avant votre rendez-vous.', 'content_en' => 'Find useful answers before your appointment.', 'button_text_fr' => 'Consulter la FAQ', 'button_text_en' => 'View FAQ', 'button_url' => '/faq', 'is_active' => true, 'sort_order' => 11],
            ['key' => 'booking_cta', 'title_fr' => 'Prête à prendre soin de votre peau ?', 'title_en' => 'Ready to care for your skin?', 'content_fr' => 'Réservez votre rendez-vous chez Asthetika et bénéficiez d’un accompagnement adapté.', 'content_en' => 'Book your appointment at Asthetika and receive care tailored to your needs.', 'button_text_fr' => 'Prendre rendez-vous', 'button_text_en' => 'Book an appointment', 'button_url' => '/booking', 'secondary_button_text_fr' => 'WhatsApp', 'secondary_button_text_en' => 'WhatsApp', 'secondary_button_url' => '/contact', 'is_active' => true, 'sort_order' => 12],
            ['key' => 'contact_cta', 'title_fr' => 'Contactez Asthetika', 'title_en' => 'Contact Asthetika', 'content_fr' => 'Pour toute question, contactez-nous par téléphone, WhatsApp ou Instagram.', 'content_en' => 'For any question, contact us by phone, WhatsApp, or Instagram.', 'button_text_fr' => 'Page contact', 'button_text_en' => 'Contact page', 'button_url' => '/contact', 'is_active' => true, 'sort_order' => 13],
        ] as $section) {
            HomepageSection::query()->updateOrCreate(['key' => $section['key']], $section);
        }

        foreach ([
            ['page_key' => 'home', 'title_fr' => 'Asthetika · Dr Aziz Sahly', 'title_en' => 'Asthetika · Dr Aziz Sahly', 'subtitle_fr' => 'Médecine esthétique et soins de la peau', 'subtitle_en' => 'Aesthetic medicine and skincare', 'description_fr' => 'Des protocoles personnalisés à La Soukra, Ariana, pour accompagner la santé et l’éclat de votre peau.', 'description_en' => 'Personalized protocols in La Soukra, Ariana, to support your skin health and radiance.', 'cta_label_fr' => 'Prendre rendez-vous', 'cta_label_en' => 'Book an appointment', 'cta_url' => '/booking', 'alt_text_fr' => 'Ambiance Asthetika', 'alt_text_en' => 'Asthetika atmosphere', 'sort_order' => 1],
            ['page_key' => 'about', 'title_fr' => 'À propos d’Asthetika', 'title_en' => 'About Asthetika', 'subtitle_fr' => 'Une approche attentive et personnalisée', 'subtitle_en' => 'Attentive and personalized care', 'description_fr' => 'Asthetika accompagne chaque patient avec écoute, précision et conseils adaptés.', 'description_en' => 'Asthetika supports each patient with attentive care, precision, and tailored guidance.', 'cta_label_fr' => 'Découvrir les services', 'cta_label_en' => 'Discover services', 'cta_url' => '/services', 'alt_text_fr' => 'À propos d’Asthetika', 'alt_text_en' => 'About Asthetika', 'sort_order' => 2],
            ['page_key' => 'services', 'title_fr' => 'Soins et protocoles Asthetika', 'title_en' => 'Asthetika treatments and protocols', 'subtitle_fr' => 'Noor & Dr Aziz', 'subtitle_en' => 'Noor & Dr Aziz', 'description_fr' => 'Découvrez les soins de la peau Noor et l’accompagnement Dr Aziz.', 'description_en' => 'Discover Noor skincare treatments and Dr Aziz guidance.', 'cta_label_fr' => 'Prendre rendez-vous', 'cta_label_en' => 'Book an appointment', 'cta_url' => '/booking', 'alt_text_fr' => 'Soins Asthetika', 'alt_text_en' => 'Asthetika treatments', 'sort_order' => 3],
            ['page_key' => 'gallery', 'title_fr' => 'Galerie', 'title_en' => 'Gallery', 'subtitle_fr' => 'Ambiance et soins Asthetika', 'subtitle_en' => 'Asthetika atmosphere and treatments', 'description_fr' => 'Aperçu de l’univers Asthetika, sans promesses exagérées ni avant/après trompeurs.', 'description_en' => 'A glimpse into the Asthetika experience, without exaggerated claims or misleading before/after promises.', 'cta_label_fr' => 'Prendre rendez-vous', 'cta_label_en' => 'Book an appointment', 'cta_url' => '/booking', 'alt_text_fr' => 'Galerie Asthetika', 'alt_text_en' => 'Asthetika gallery', 'sort_order' => 4],
            ['page_key' => 'testimonials', 'title_fr' => 'Témoignages', 'title_en' => 'Testimonials', 'subtitle_fr' => 'Retours d’expérience', 'subtitle_en' => 'Client feedback', 'description_fr' => 'Des retours simples et authentiques sur l’accompagnement Asthetika.', 'description_en' => 'Simple and authentic feedback about the Asthetika experience.', 'cta_label_fr' => 'Voir les services', 'cta_label_en' => 'View services', 'cta_url' => '/services', 'alt_text_fr' => 'Témoignages Asthetika', 'alt_text_en' => 'Asthetika testimonials', 'sort_order' => 5],
            ['page_key' => 'faq', 'title_fr' => 'Questions fréquentes', 'title_en' => 'Frequently asked questions', 'subtitle_fr' => 'Informations utiles', 'subtitle_en' => 'Useful information', 'description_fr' => 'Retrouvez les réponses aux questions les plus fréquentes avant votre rendez-vous.', 'description_en' => 'Find answers to common questions before your appointment.', 'cta_label_fr' => 'Nous contacter', 'cta_label_en' => 'Contact us', 'cta_url' => '/contact', 'alt_text_fr' => 'FAQ Asthetika', 'alt_text_en' => 'Asthetika FAQ', 'sort_order' => 6],
            ['page_key' => 'contact', 'title_fr' => 'Contactez Asthetika', 'title_en' => 'Contact Asthetika', 'subtitle_fr' => 'Rendez-vous et informations', 'subtitle_en' => 'Appointments and information', 'description_fr' => 'Contactez-nous par téléphone, WhatsApp ou Instagram pour organiser votre rendez-vous.', 'description_en' => 'Contact us by phone, WhatsApp, or Instagram to organize your appointment.', 'cta_label_fr' => 'Prendre rendez-vous', 'cta_label_en' => 'Book an appointment', 'cta_url' => '/booking', 'alt_text_fr' => 'Contact Asthetika', 'alt_text_en' => 'Asthetika contact', 'sort_order' => 7],
            ['page_key' => 'consultation', 'title_fr' => 'Consultation', 'title_en' => 'Consultation', 'subtitle_fr' => 'Conseils personnalisés', 'subtitle_en' => 'Personalized guidance', 'description_fr' => 'Un échange pour mieux comprendre vos besoins et vous orienter vers un protocole adapté.', 'description_en' => 'A conversation to better understand your needs and guide you toward a suitable protocol.', 'cta_label_fr' => 'Commencer', 'cta_label_en' => 'Start', 'cta_url' => '/consultation', 'alt_text_fr' => 'Consultation Asthetika', 'alt_text_en' => 'Asthetika consultation', 'sort_order' => 8],
            ['page_key' => 'booking', 'title_fr' => 'Réservation', 'title_en' => 'Booking', 'subtitle_fr' => 'Choisissez votre soin et votre créneau', 'subtitle_en' => 'Choose your treatment and time', 'description_fr' => 'Réservez votre rendez-vous en quelques étapes simples.', 'description_en' => 'Book your appointment in a few simple steps.', 'cta_label_fr' => 'Voir les services', 'cta_label_en' => 'View services', 'cta_url' => '/services', 'alt_text_fr' => 'Réservation Asthetika', 'alt_text_en' => 'Asthetika booking', 'sort_order' => 9],
            ['page_key' => 'recommender', 'title_fr' => 'IA Recommendation', 'title_en' => 'AI Recommendation', 'subtitle_fr' => 'Orientation intelligente', 'subtitle_en' => 'Smart guidance', 'description_fr' => 'Un assistant d’orientation pour vous aider à identifier les soins à discuter avec Asthetika.', 'description_en' => 'A guidance assistant to help identify treatments to discuss with Asthetika.', 'cta_label_fr' => 'Commencer', 'cta_label_en' => 'Start', 'cta_url' => '/recommender', 'alt_text_fr' => 'IA Recommendation Asthetika', 'alt_text_en' => 'Asthetika AI Recommendation', 'sort_order' => 10],
            ['page_key' => 'policies', 'title_fr' => 'Politiques', 'title_en' => 'Policies', 'subtitle_fr' => 'Informations et conditions', 'subtitle_en' => 'Information and terms', 'description_fr' => 'Retrouvez les informations utiles liées à la réservation, la confidentialité et les conditions générales.', 'description_en' => 'Find useful information related to booking, privacy, and terms.', 'cta_label_fr' => 'Nous contacter', 'cta_label_en' => 'Contact us', 'cta_url' => '/contact', 'alt_text_fr' => 'Politiques Asthetika', 'alt_text_en' => 'Asthetika policies', 'sort_order' => 11],
        ] as $hero) {
            PageHero::query()->updateOrCreate(['page_key' => $hero['page_key']], $hero + ['image_path' => null, 'mobile_image_path' => null, 'overlay_opacity' => 0.35, 'is_active' => true]);
        }

        foreach ([
            ['title_fr' => 'Asthetika · Dr Aziz Sahly', 'title_en' => 'Asthetika · Dr Aziz Sahly', 'subtitle_fr' => 'Médecine esthétique et soins de la peau', 'subtitle_en' => 'Aesthetic medicine and skincare', 'description_fr' => 'Des soins personnalisés à La Soukra, Ariana, dans une approche professionnelle et attentive.', 'description_en' => 'Personalized care in La Soukra, Ariana, with a professional and attentive approach.', 'cta_label_fr' => 'Prendre rendez-vous', 'cta_label_en' => 'Book an appointment', 'cta_url' => '/booking', 'sort_order' => 1, 'alt_text_fr' => 'Asthetika à La Soukra', 'alt_text_en' => 'Asthetika in La Soukra'],
            ['title_fr' => 'Noor', 'title_en' => 'Noor', 'subtitle_fr' => 'Soins de la peau & Hydrafacial', 'subtitle_en' => 'Skincare & Hydrafacial', 'description_fr' => 'Hydrafacial, protocoles personnalisés et conseils adaptés pour accompagner l’éclat de votre peau.', 'description_en' => 'Hydrafacial, personalized protocols, and tailored advice to support your skin radiance.', 'cta_label_fr' => 'Découvrir Noor', 'cta_label_en' => 'Discover Noor', 'cta_url' => '/services#noor', 'sort_order' => 2, 'alt_text_fr' => 'Soins Noor', 'alt_text_en' => 'Noor treatments'],
            ['title_fr' => 'Dr Aziz', 'title_en' => 'Dr Aziz', 'subtitle_fr' => 'Consultation et accompagnement', 'subtitle_en' => 'Consultation and guidance', 'description_fr' => 'Un accompagnement médico-esthétique professionnel pour définir une prise en charge adaptée.', 'description_en' => 'Professional medical-aesthetic guidance to define suitable care.', 'cta_label_fr' => 'Découvrir Dr Aziz', 'cta_label_en' => 'Discover Dr Aziz', 'cta_url' => '/services#dr-aziz', 'sort_order' => 3, 'alt_text_fr' => 'Dr Aziz Sahly', 'alt_text_en' => 'Dr Aziz Sahly'],
            ['title_fr' => 'Réservez votre rendez-vous', 'title_en' => 'Book your appointment', 'subtitle_fr' => 'En ligne ou par WhatsApp', 'subtitle_en' => 'Online or by WhatsApp', 'description_fr' => 'Choisissez votre soin, votre créneau et confirmez votre rendez-vous facilement.', 'description_en' => 'Choose your treatment, your time slot, and confirm your appointment easily.', 'cta_label_fr' => 'Réserver', 'cta_label_en' => 'Book now', 'cta_url' => '/booking', 'sort_order' => 4, 'alt_text_fr' => 'Réservation Asthetika', 'alt_text_en' => 'Asthetika booking'],
        ] as $slide) {
            HomeBannerSlide::query()->updateOrCreate(['title_en' => $slide['title_en']], $slide + ['image_path' => null, 'mobile_image_path' => null, 'is_active' => true]);
        }

        AboutPage::query()->updateOrCreate(['id' => 1], [
            'title_fr' => 'À propos d’Asthetika', 'title_en' => 'About Asthetika',
            'intro_fr' => 'Asthetika est un espace dédié à la médecine esthétique et aux soins de la peau, dirigé par Dr Aziz Sahly.', 'intro_en' => 'Asthetika is a space dedicated to aesthetic medicine and skincare, led by Dr Aziz Sahly.',
            'story_fr' => 'Situé à La Soukra, Ariana, Asthetika accompagne chaque patient avec des protocoles personnalisés, une écoute attentive et une approche centrée sur la santé de la peau.',
            'story_en' => 'Located in La Soukra, Ariana, Asthetika supports each patient with personalized protocols, attentive care, and a skin-health-focused approach.',
            'philosophy_fr' => 'Sublimer la peau avec naturel, précision et sécurité.', 'philosophy_en' => 'Enhancing the skin with natural-looking, precise, and safe care.',
            'qualifications_fr' => 'Médecine esthétique, protocoles cutanés personnalisés, hygiène médicale et accompagnement professionnel.', 'qualifications_en' => 'Aesthetic medicine, personalized skin protocols, medical hygiene, and professional care.', 'is_published' => true,
        ]);

        $resolveImagePath = static function (?string $path): ?string {
            if (blank($path)) {
                return null;
            }

            if (file_exists(public_path($path)) || file_exists(public_path('storage/'.$path)) || Storage::disk('public')->exists($path)) {
                return $path;
            }

            return null;
        };

        $galleryItems = [
            ['title_fr' => 'Soin Hydrafacial', 'title_en' => 'Hydrafacial treatment', 'caption_fr' => 'Un soin complet pour nettoyer, exfolier et accompagner l’éclat de la peau.', 'caption_en' => 'A complete treatment to cleanse, exfoliate, and support skin radiance.', 'category' => 'noor', 'image_path' => null, 'is_before_after' => false, 'is_featured' => true, 'is_active' => true, 'sort_order' => 1],
            ['title_fr' => 'Hydrafacial Détoxifiant', 'title_en' => 'Detoxifying Hydrafacial', 'caption_fr' => 'Un protocole purifiant pensé pour les peaux ternes, obstruées ou sujettes aux imperfections.', 'caption_en' => 'A purifying protocol designed for dull, congested, or blemish-prone skin.', 'category' => 'noor', 'image_path' => null, 'is_before_after' => false, 'is_featured' => true, 'is_active' => true, 'sort_order' => 2],
            ['title_fr' => 'Protocole éclat personnalisé', 'title_en' => 'Personalized glow protocol', 'caption_fr' => 'Une approche progressive et adaptée selon les besoins de la peau.', 'caption_en' => 'A progressive approach tailored to the skin’s needs.', 'category' => 'noor', 'image_path' => null, 'is_before_after' => false, 'is_featured' => true, 'is_active' => true, 'sort_order' => 3],
            ['title_fr' => 'Consultation peau', 'title_en' => 'Skin consultation', 'caption_fr' => 'Un échange pour mieux comprendre les attentes et orienter le protocole adapté.', 'caption_en' => 'A conversation to better understand expectations and guide the suitable protocol.', 'category' => 'dr-aziz', 'image_path' => null, 'is_before_after' => false, 'is_featured' => true, 'is_active' => true, 'sort_order' => 4],
            ['title_fr' => 'Espace Asthetika', 'title_en' => 'Asthetika space', 'caption_fr' => 'Un cadre calme et professionnel pour accompagner chaque rendez-vous.', 'caption_en' => 'A calm and professional setting for every appointment.', 'category' => 'asthetika', 'image_path' => null, 'is_before_after' => false, 'is_featured' => false, 'is_active' => true, 'sort_order' => 5],
            ['title_fr' => 'Préparation du soin', 'title_en' => 'Treatment preparation', 'caption_fr' => 'Chaque soin est préparé avec attention, hygiène et précision.', 'caption_en' => 'Each treatment is prepared with care, hygiene, and precision.', 'category' => 'noor', 'image_path' => null, 'is_before_after' => false, 'is_featured' => false, 'is_active' => true, 'sort_order' => 6],
            ['title_fr' => 'Conseils personnalisés', 'title_en' => 'Personalized advice', 'caption_fr' => 'Des recommandations adaptées à votre peau, votre routine et vos objectifs.', 'caption_en' => 'Recommendations adapted to your skin, routine, and goals.', 'category' => 'dr-aziz', 'image_path' => null, 'is_before_after' => false, 'is_featured' => false, 'is_active' => true, 'sort_order' => 7],
            ['title_fr' => 'Routine post-soin', 'title_en' => 'Post-treatment routine', 'caption_fr' => 'Des conseils simples pour prolonger le confort et l’équilibre de la peau.', 'caption_en' => 'Simple advice to support comfort and skin balance after treatment.', 'category' => 'asthetika', 'image_path' => null, 'is_before_after' => false, 'is_featured' => false, 'is_active' => true, 'sort_order' => 8],
        ];

        foreach ($galleryItems as $item) {
            $item['image_path'] = $resolveImagePath($item['image_path']);
            GalleryItem::query()->updateOrCreate(['title_en' => $item['title_en']], $item);
        }

        foreach ([
            ['question_fr' => 'Quel soin choisir ?', 'question_en' => 'Which treatment should I choose?', 'answer_fr' => 'Si vous hésitez, une consultation ou un échange avec Asthetika permet de mieux comprendre votre peau, vos attentes et de vous orienter vers le protocole le plus adapté.', 'answer_en' => 'If you are unsure, a consultation or conversation with Asthetika helps understand your skin, expectations, and guide you toward the most suitable protocol.', 'category' => 'general', 'sort_order' => 1],
            ['question_fr' => 'Quelle est la différence entre Noor et Dr Aziz ?', 'question_en' => 'What is the difference between Noor and Dr Aziz?', 'answer_fr' => 'Noor regroupe les soins de la peau, Hydrafacial et protocoles esthétiques personnalisés. Dr Aziz correspond à l’accompagnement médico-esthétique, aux conseils personnalisés et au suivi professionnel par Dr Aziz Sahly.', 'answer_en' => 'Noor covers skincare, Hydrafacial, and personalized aesthetic protocols. Dr Aziz refers to medical-aesthetic guidance, personalized advice, and professional follow-up by Dr Aziz Sahly.', 'category' => 'general', 'sort_order' => 2],
            ['question_fr' => 'Puis-je réserver via WhatsApp ?', 'question_en' => 'Can I book via WhatsApp?', 'answer_fr' => 'Oui. Vous pouvez réserver ou demander des informations via WhatsApp au +216 26 500 507, ou utiliser le formulaire de réservation en ligne.', 'answer_en' => 'Yes. You can book or request information via WhatsApp at +216 26 500 507, or use the online booking form.', 'category' => 'booking', 'sort_order' => 3],
            ['question_fr' => 'Où se trouve Asthetika ?', 'question_en' => 'Where is Asthetika located?', 'answer_fr' => 'Asthetika se trouve à La Soukra, Ariana, Tunisie. Vous pouvez retrouver l’itinéraire depuis la page Contact.', 'answer_en' => 'Asthetika is located in La Soukra, Ariana, Tunisia. You can find directions from the Contact page.', 'category' => 'location', 'sort_order' => 4],
            ['question_fr' => 'Les soins sont-ils sur rendez-vous ?', 'question_en' => 'Are treatments by appointment?', 'answer_fr' => 'Oui, les consultations et soins sont organisés sur rendez-vous afin de garantir une prise en charge attentive.', 'answer_en' => 'Yes, consultations and treatments are by appointment to ensure attentive care.', 'category' => 'booking', 'sort_order' => 5],
            ['question_fr' => 'Comment se préparer avant un Hydrafacial ?', 'question_en' => 'How should I prepare before a Hydrafacial?', 'answer_fr' => 'Venez avec une peau propre si possible et évitez les soins agressifs juste avant le rendez-vous. En cas de doute ou de traitement cutané en cours, signalez-le avant le soin.', 'answer_en' => 'Come with clean skin if possible and avoid aggressive treatments right before the appointment. If you are unsure or currently using a skin treatment, mention it before the session.', 'category' => 'noor', 'sort_order' => 6],
            ['question_fr' => 'Que faire après un soin ?', 'question_en' => 'What should I do after a treatment?', 'answer_fr' => 'Après un soin, suivez les recommandations données sur place, hydratez votre peau et évitez les gestes agressifs. Les conseils peuvent varier selon votre peau et le protocole réalisé.', 'answer_en' => 'After a treatment, follow the recommendations given during your visit, hydrate your skin, and avoid aggressive skincare steps. Advice may vary depending on your skin and the protocol performed.', 'category' => 'noor', 'sort_order' => 7],
            ['question_fr' => 'Combien de temps dure un soin ?', 'question_en' => 'How long does a treatment take?', 'answer_fr' => 'La durée dépend du soin choisi. Les Hydrafacial indiqués durent environ 1 heure, tandis que les consultations ou suivis peuvent être plus courts.', 'answer_en' => 'Duration depends on the selected treatment. Listed Hydrafacial treatments take around 1 hour, while consultations or follow-ups may be shorter.', 'category' => 'services', 'sort_order' => 8],
            ['question_fr' => 'Les tarifs sont-ils fixes ?', 'question_en' => 'Are prices fixed?', 'answer_fr' => 'Les tarifs affichés concernent les soins précisés. Pour certains accompagnements ou protocoles personnalisés, le tarif peut être confirmé après échange ou consultation.', 'answer_en' => 'Displayed prices apply to the listed treatments. For certain personalized protocols or guidance, pricing may be confirmed after discussion or consultation.', 'category' => 'services', 'sort_order' => 9],
            ['question_fr' => 'Puis-je annuler ou déplacer mon rendez-vous ?', 'question_en' => 'Can I cancel or reschedule my appointment?', 'answer_fr' => 'Oui. Merci de prévenir le plus tôt possible, idéalement au moins 24h à l’avance, afin de libérer le créneau.', 'answer_en' => 'Yes. Please notify us as early as possible, ideally at least 24 hours in advance, so the slot can be released.', 'category' => 'booking', 'sort_order' => 10],
            ['question_fr' => 'Les informations du site remplacent-elles une consultation ?', 'question_en' => 'Does the website information replace a consultation?', 'answer_fr' => 'Non. Les informations du site sont fournies à titre informatif et ne remplacent pas une consultation personnalisée ou un avis médical.', 'answer_en' => 'No. Website information is provided for informational purposes and does not replace a personalized consultation or medical advice.', 'category' => 'medical', 'sort_order' => 11],
            ['question_fr' => 'Comment fonctionne IA Recommendation ?', 'question_en' => 'How does AI Recommendation work?', 'answer_fr' => 'L’outil d’orientation IA peut aider à préparer votre demande en suggérant des pistes à discuter avec Asthetika. Il ne remplace pas l’avis d’un professionnel.', 'answer_en' => 'The AI guidance tool can help prepare your request by suggesting topics to discuss with Asthetika. It does not replace professional advice.', 'category' => 'ai', 'sort_order' => 12],
        ] as $faq) {
            Faq::query()->updateOrCreate(['question_en' => $faq['question_en']], $faq + ['is_active' => true]);
        }

        foreach ([
            ['title_fr' => 'Politique d’annulation', 'title_en' => 'Cancellation policy', 'slug' => 'cancellation-policy', 'content_fr' => "Merci de prévenir au moins 24h à l’avance en cas d’annulation ou de report. Cela nous permet de réorganiser les rendez-vous et de proposer le créneau à une autre personne.\n\nEn cas d’empêchement de dernière minute, contactez Asthetika par téléphone ou WhatsApp au +216 26 500 507.", 'content_en' => "Please notify us at least 24 hours in advance for cancellations or rescheduling. This helps us reorganize appointments and offer the slot to another client.\n\nIn case of a last-minute issue, contact Asthetika by phone or WhatsApp at +216 26 500 507.", 'sort_order' => 1],
            ['title_fr' => 'Politique de confidentialité', 'title_en' => 'Privacy policy', 'slug' => 'privacy-policy', 'content_fr' => "Les informations transmises via le site ou lors de la prise de rendez-vous sont utilisées uniquement pour gérer votre demande, votre rendez-vous et le suivi de votre prise en charge.\n\nAsthetika ne vend pas vos données personnelles. Vous pouvez demander la modification ou la suppression de vos informations en nous contactant.", 'content_en' => "Information submitted through the website or during booking is used only to manage your request, appointment, and follow-up.\n\nAsthetika does not sell personal data. You may request modification or deletion of your information by contacting us.", 'sort_order' => 2],
            ['title_fr' => 'Conditions générales', 'title_en' => 'Terms of service', 'slug' => 'terms-of-service', 'content_fr' => "Les informations du site sont fournies à titre informatif et ne remplacent pas une consultation personnalisée. Les soins, conseils et recommandations sont adaptés selon chaque situation.\n\nL’utilisation du site implique l’acceptation de ces conditions.", 'content_en' => "The information on this website is provided for informational purposes and does not replace a personalized consultation. Treatments, advice, and recommendations are adapted to each case.\n\nUsing the website implies acceptance of these terms.", 'sort_order' => 3],
            ['title_fr' => 'Politique de réservation', 'title_en' => 'Booking policy', 'slug' => 'booking-policy', 'content_fr' => "La réservation en ligne permet de choisir un soin, une date et un créneau disponibles. Asthetika peut vous contacter si une précision est nécessaire avant le rendez-vous.\n\nMerci de vérifier vos coordonnées avant confirmation.", 'content_en' => "Online booking allows you to choose a treatment, date, and available time slot. Asthetika may contact you if clarification is needed before the appointment.\n\nPlease check your contact details before confirmation.", 'sort_order' => 4],
            ['title_fr' => 'Consentement image', 'title_en' => 'Image consent policy', 'slug' => 'image-consent-policy', 'content_fr' => "Aucune photo identifiable ne doit être utilisée publiquement sans accord explicite. Les images publiées doivent respecter la confidentialité et l’accord de la personne concernée.\n\nVous pouvez demander le retrait d’une image vous concernant en contactant Asthetika.", 'content_en' => "No identifiable photo should be used publicly without explicit consent. Published images must respect privacy and the agreement of the person concerned.\n\nYou may request removal of an image concerning you by contacting Asthetika.", 'sort_order' => 5],
            ['title_fr' => 'Information médicale', 'title_en' => 'Medical disclaimer', 'slug' => 'medical-disclaimer', 'content_fr' => "Les contenus du site, y compris les informations liées aux soins et à l’orientation IA, ne remplacent pas une consultation médicale personnalisée. Toute recommandation doit être adaptée à votre situation.\n\nEn cas de doute, demandez un avis professionnel.", 'content_en' => "Website content, including treatment information and AI guidance, does not replace a personalized medical consultation. Any recommendation must be adapted to your situation.\n\nIf in doubt, seek professional advice.", 'sort_order' => 6],
        ] as $policy) {
            Policy::query()->updateOrCreate(['slug' => $policy['slug']], $policy + [
                'meta_title_fr' => $policy['title_fr'].' | Asthetika',
                'meta_title_en' => $policy['title_en'].' | Asthetika',
                'meta_description_fr' => 'Informations Asthetika concernant '.mb_strtolower($policy['title_fr']).'.',
                'meta_description_en' => 'Asthetika information about '.mb_strtolower($policy['title_en']).'.',
                'is_active' => true,
            ]);
        }

        $serviceIdsBySlug = \App\Models\Service::query()
            ->whereIn('slug', ['hydrafacial-essentiel', 'hydrafacial-detoxifiant', 'consultation-dr-aziz', 'consultation-peau-noor', 'suivi-post-soin'])
            ->pluck('id', 'slug');

        $testimonials = [
            ['client_name' => 'Cliente Asthetika', 'title_fr' => 'Accompagnement professionnel', 'title_en' => 'Professional care', 'content_fr' => 'Accueil attentif, explications claires et soin adapté à mes besoins.', 'content_en' => 'Attentive welcome, clear explanations, and care adapted to my needs.', 'rating' => 5, 'service_slug' => 'consultation-dr-aziz', 'is_featured' => true, 'sort_order' => 1],
            ['client_name' => 'Cliente Noor', 'title_fr' => 'Soin agréable', 'title_en' => 'Pleasant treatment', 'content_fr' => 'Un soin agréable avec des conseils utiles pour ma routine.', 'content_en' => 'A pleasant treatment with helpful advice for my routine.', 'rating' => 5, 'service_slug' => 'hydrafacial-essentiel', 'is_featured' => true, 'sort_order' => 2],
            ['client_name' => 'Patiente Dr Aziz', 'title_fr' => 'Conseils clairs', 'title_en' => 'Clear guidance', 'content_fr' => 'Des conseils clairs et un accompagnement rassurant.', 'content_en' => 'Clear advice and reassuring support.', 'rating' => 5, 'service_slug' => 'consultation-dr-aziz', 'is_featured' => true, 'sort_order' => 3],
            ['client_name' => 'Cliente Hydrafacial', 'title_fr' => 'Expérience soignée', 'title_en' => 'Thoughtful experience', 'content_fr' => 'Le soin a été réalisé avec douceur, hygiène et beaucoup d’attention.', 'content_en' => 'The treatment was carried out with gentleness, hygiene, and care.', 'rating' => 5, 'service_slug' => 'hydrafacial-detoxifiant', 'is_featured' => false, 'sort_order' => 4],
            ['client_name' => 'Cliente Consultation', 'title_fr' => 'Orientation utile', 'title_en' => 'Helpful guidance', 'content_fr' => 'J’ai apprécié les explications et l’orientation vers un protocole adapté.', 'content_en' => 'I appreciated the explanations and guidance toward a suitable protocol.', 'rating' => 4, 'service_slug' => 'consultation-peau-noor', 'is_featured' => false, 'sort_order' => 5],
            ['client_name' => 'Cliente Suivi', 'title_fr' => 'Suivi rassurant', 'title_en' => 'Reassuring follow-up', 'content_fr' => 'Un suivi simple, clair et rassurant après mon rendez-vous.', 'content_en' => 'Simple, clear, and reassuring follow-up after my appointment.', 'rating' => 5, 'service_slug' => 'suivi-post-soin', 'is_featured' => false, 'sort_order' => 6],
        ];

        foreach ($testimonials as $testimonial) {
            $serviceSlug = $testimonial['service_slug'];
            unset($testimonial['service_slug']);
            $testimonial['service_id'] = $serviceIdsBySlug[$serviceSlug] ?? null;
            $testimonial['is_active'] = true;

            Testimonial::query()->updateOrCreate(
                ['client_name' => $testimonial['client_name'], 'title_en' => $testimonial['title_en']],
                $testimonial,
            );
        }
    }
}
